"""Phase 10: feature flags, homepage banners, announcements

Revision ID: 034cb2aa8fc1
Revises: 39ad6de63086
Create Date: 2026-08-13 19:32:17.272980

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "034cb2aa8fc1"
down_revision: str | None = "39ad6de63086"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feature_flags_key"), "feature_flags", ["key"], unique=True)
    op.create_table(
        "homepage_banners",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title_az", sa.String(length=200), nullable=False),
        sa.Column("subtitle_az", sa.String(length=300), nullable=False),
        sa.Column("image_url", sa.String(length=1000), nullable=True),
        sa.Column("link_url", sa.String(length=1000), nullable=True),
        sa.Column("cta_label_az", sa.String(length=100), nullable=True),
        sa.Column("badge_az", sa.String(length=100), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_homepage_banners_active"), "homepage_banners", ["active"], unique=False
    )
    op.create_table(
        "admin_announcements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.Column("link", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["admin_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin_announcements")
    op.drop_index(op.f("ix_homepage_banners_active"), table_name="homepage_banners")
    op.drop_table("homepage_banners")
    op.drop_index(op.f("ix_feature_flags_key"), table_name="feature_flags")
    op.drop_table("feature_flags")
    # ### end Alembic commands ###
