"""phase14 favorite collections

Revision ID: 0cb5ce33bd37
Revises: bbc830940b0b
Create Date: 2026-08-15 19:17:28.841896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0cb5ce33bd37'
down_revision: Union[str, None] = 'bbc830940b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_collections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_collection_name')
    )
    op.create_index(op.f('ix_favorite_collections_user_id'), 'favorite_collections', ['user_id'], unique=False)
    op.add_column('favorites', sa.Column('collection_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_favorites_collection_id'), 'favorites', ['collection_id'], unique=False)
    op.create_foreign_key('fk_favorites_collection_id', 'favorites', 'favorite_collections', ['collection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_favorites_collection_id', 'favorites', type_='foreignkey')
    op.drop_index(op.f('ix_favorites_collection_id'), table_name='favorites')
    op.drop_column('favorites', 'collection_id')
    op.drop_index(op.f('ix_favorite_collections_user_id'), table_name='favorite_collections')
    op.drop_table('favorite_collections')
    # ### end Alembic commands ###
