"""phase14 webhook event log

Revision ID: 38bab1bdf849
Revises: 6c1ecabc29a8
Create Date: 2026-08-15 20:18:54.989281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '38bab1bdf849'
down_revision: Union[str, None] = '6c1ecabc29a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
