"""Phase 10: payments, promotion products, media thumbnails

Revision ID: 39ad6de63086
Revises: bcbcee54d3f9
Create Date: 2026-08-13 19:30:27.155302

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "39ad6de63086"
down_revision: str | None = "bcbcee54d3f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promotion_products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("label_az", sa.String(length=100), nullable=False),
        sa.Column("description_az", sa.String(length=300), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_premium_tier", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_promotion_products_code"), "promotion_products", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_promotion_products_enabled"),
        "promotion_products",
        ["enabled"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("wallet_transaction_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=200), nullable=True),
        sa.Column("checkout_url", sa.String(length=1000), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["wallet_transaction_id"], ["wallet_transactions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payments_idempotency_key"),
        "payments",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_payments_provider_payment_id"),
        "payments",
        ["provider_payment_id"],
        unique=False,
    )
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_payments_wallet_transaction_id"),
        "payments",
        ["wallet_transaction_id"],
        unique=False,
    )
    op.create_table(
        "promotion_purchases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("price_paid", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "starts_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["promotion_products.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_promotion_purchases_product_id"),
        "promotion_purchases",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_promotion_purchases_property_id"),
        "promotion_purchases",
        ["property_id"],
        unique=False,
    )
    op.create_index(
        "ix_promotion_purchases_property_status",
        "promotion_purchases",
        ["property_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_promotion_purchases_status"),
        "promotion_purchases",
        ["status"],
        unique=False,
    )
    op.add_column(
        "property_media",
        sa.Column("thumbnail_url", sa.String(length=1000), nullable=True),
    )
    # ### end Alembic commands ###

    # Seed default promotion products (prices/durations are admin-configurable).
    promotion_products = sa.table(
        "promotion_products",
        sa.column("id", sa.Uuid()),
        sa.column("code", sa.String()),
        sa.column("label_az", sa.String()),
        sa.column("description_az", sa.String()),
        sa.column("price", sa.Integer()),
        sa.column("duration_days", sa.Integer()),
        sa.column("sort_order", sa.Integer()),
        sa.column("is_premium_tier", sa.Boolean()),
        sa.column("enabled", sa.Boolean()),
    )
    op.bulk_insert(
        promotion_products,
        [
            {
                "id": "11111111-1111-4111-8111-111111111101",
                "code": "standard",
                "label_az": "Standart",
                "description_az": "7 gün standart önə çıxarış",
                "price": 500,
                "duration_days": 7,
                "sort_order": 1,
                "is_premium_tier": False,
                "enabled": True,
            },
            {
                "id": "11111111-1111-4111-8111-111111111102",
                "code": "premium",
                "label_az": "Premium",
                "description_az": "14 gün premium yerləşdirmə",
                "price": 1500,
                "duration_days": 14,
                "sort_order": 2,
                "is_premium_tier": True,
                "enabled": True,
            },
            {
                "id": "11111111-1111-4111-8111-111111111103",
                "code": "vip",
                "label_az": "VIP",
                "description_az": "30 gün VIP nişanı",
                "price": 3000,
                "duration_days": 30,
                "sort_order": 3,
                "is_premium_tier": True,
                "enabled": True,
            },
            {
                "id": "11111111-1111-4111-8111-111111111104",
                "code": "top",
                "label_az": "Top",
                "description_az": "30 gün siyahının ən yuxarısı",
                "price": 5000,
                "duration_days": 30,
                "sort_order": 4,
                "is_premium_tier": True,
                "enabled": True,
            },
            {
                "id": "11111111-1111-4111-8111-111111111105",
                "code": "urgent",
                "label_az": "Təcili",
                "description_az": "7 gün təcili nişanı",
                "price": 7000,
                "duration_days": 7,
                "sort_order": 5,
                "is_premium_tier": False,
                "enabled": True,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("property_media", "thumbnail_url")
    op.drop_index(
        op.f("ix_promotion_purchases_status"), table_name="promotion_purchases"
    )
    op.drop_index(
        "ix_promotion_purchases_property_status", table_name="promotion_purchases"
    )
    op.drop_index(
        op.f("ix_promotion_purchases_property_id"), table_name="promotion_purchases"
    )
    op.drop_index(
        op.f("ix_promotion_purchases_product_id"), table_name="promotion_purchases"
    )
    op.drop_table("promotion_purchases")
    op.drop_index(op.f("ix_payments_wallet_transaction_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_provider_payment_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_idempotency_key"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(
        op.f("ix_promotion_products_enabled"), table_name="promotion_products"
    )
    op.drop_index(op.f("ix_promotion_products_code"), table_name="promotion_products")
    op.drop_table("promotion_products")
    # ### end Alembic commands ###
