"""phase14 agency invites

Revision ID: 40affa281171
Revises: c9433bb97b4a
Create Date: 2026-08-15 20:36:34.843715

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "40affa281171"
down_revision: str | None = "c9433bb97b4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agency_invites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agency_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agency_id"], ["agencies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agency_invites_agency_id"),
        "agency_invites",
        ["agency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agency_invites_email"), "agency_invites", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_agency_invites_status"), "agency_invites", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_agency_invites_token"), "agency_invites", ["token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agency_invites_token"), table_name="agency_invites")
    op.drop_index(op.f("ix_agency_invites_status"), table_name="agency_invites")
    op.drop_index(op.f("ix_agency_invites_email"), table_name="agency_invites")
    op.drop_index(op.f("ix_agency_invites_agency_id"), table_name="agency_invites")
    op.drop_table("agency_invites")
    # ### end Alembic commands ###
