"""Add notification model and user relationship

Revision ID: 42d8525bb4fd
Revises: df2995367ac1
Create Date: 2026-08-11 08:35:20.790681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '42d8525bb4fd'
down_revision: Union[str, None] = 'df2995367ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
