"""phase14 listing quality score

Revision ID: 6c1ecabc29a8
Revises: e39cd8fe883f
Create Date: 2026-08-15 20:11:57.452440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c1ecabc29a8'
down_revision: Union[str, None] = 'e39cd8fe883f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('quality_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'quality_score')
    # ### end Alembic commands ###
