"""phase5 location catalog and search filters

Revision ID: 9295efd6838c
Revises: a1b2c3d4e5f6
Create Date: 2026-08-12 18:24:21.461979

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9295efd6838c"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_places",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("name_az", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("district", sa.String(length=100), nullable=True),
        sa.Column("metro", sa.String(length=100), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["location_places.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "slug", name="uq_location_kind_slug"),
    )
    op.create_index(
        "ix_location_kind_active",
        "location_places",
        ["kind", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_location_kind_city", "location_places", ["kind", "city"], unique=False
    )
    op.create_index("ix_location_name", "location_places", ["name_az"], unique=False)
    op.create_index(
        op.f("ix_location_places_kind"), "location_places", ["kind"], unique=False
    )
    op.add_column(
        "property_locations",
        sa.Column("landmark", sa.String(length=150), nullable=True),
    )
    op.add_column(
        "property_locations", sa.Column("street", sa.String(length=150), nullable=True)
    )
    op.create_index(
        op.f("ix_property_locations_landmark"),
        "property_locations",
        ["landmark"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_property_locations_landmark"), table_name="property_locations"
    )
    op.drop_column("property_locations", "street")
    op.drop_column("property_locations", "landmark")
    op.drop_index(op.f("ix_location_places_kind"), table_name="location_places")
    op.drop_index("ix_location_name", table_name="location_places")
    op.drop_index("ix_location_kind_city", table_name="location_places")
    op.drop_index("ix_location_kind_active", table_name="location_places")
    op.drop_table("location_places")
    # ### end Alembic commands ###
