"""phase15 advertising system

Revision ID: ac2100644a2a
Revises: 40affa281171
Create Date: 2026-08-16 09:27:58.396390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac2100644a2a'
down_revision: Union[str, None] = '40affa281171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('advertiser', sa.String(length=200), nullable=False),
    sa.Column('placement', sa.String(length=32), nullable=False),
    sa.Column('desktop_creative_url', sa.String(length=1000), nullable=False),
    sa.Column('mobile_creative_url', sa.String(length=1000), nullable=True),
    sa.Column('alt_text', sa.String(length=300), nullable=True),
    sa.Column('destination_url', sa.String(length=1000), nullable=False),
    sa.Column('open_in_new_tab', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_targeting', sa.String(length=16), nullable=False),
    sa.Column('city_targeting', sa.JSON(), nullable=False),
    sa.Column('property_category_targeting', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_campaigns_archived'), 'ad_campaigns', ['archived'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_end_at'), 'ad_campaigns', ['end_at'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_placement'), 'ad_campaigns', ['placement'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_start_at'), 'ad_campaigns', ['start_at'], unique=False)
    op.create_table('ad_daily_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('unique_impressions', sa.Integer(), nullable=False),
    sa.Column('unique_clicks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'date', name='uq_ad_daily_stats_campaign_date')
    )
    op.create_index(op.f('ix_ad_daily_stats_campaign_id'), 'ad_daily_stats', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ad_daily_stats_date'), 'ad_daily_stats', ['date'], unique=False)
    op.create_table('ad_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('session_key', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_events_campaign_id'), 'ad_events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ad_events_created_at'), 'ad_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ad_events_event_type'), 'ad_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ad_events_session_key'), 'ad_events', ['session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_events_session_key'), table_name='ad_events')
    op.drop_index(op.f('ix_ad_events_event_type'), table_name='ad_events')
    op.drop_index(op.f('ix_ad_events_created_at'), table_name='ad_events')
    op.drop_index(op.f('ix_ad_events_campaign_id'), table_name='ad_events')
    op.drop_table('ad_events')
    op.drop_index(op.f('ix_ad_daily_stats_date'), table_name='ad_daily_stats')
    op.drop_index(op.f('ix_ad_daily_stats_campaign_id'), table_name='ad_daily_stats')
    op.drop_table('ad_daily_stats')
    op.drop_index(op.f('ix_ad_campaigns_start_at'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_placement'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_end_at'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_archived'), table_name='ad_campaigns')
    op.drop_table('ad_campaigns')
    # ### end Alembic commands ###
