"""add construction_year heating furnished to properties

Revision ID: b7c3e9d94599
Revises: cb41b0b14272
Create Date: 2026-08-11 03:27:22.591002

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'b7c3e9d94599'
down_revision: str | None = 'cb41b0b14272'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('furnished', sa.Boolean(), nullable=False))
    op.add_column('properties', sa.Column('heating', sa.String(length=120), nullable=True))
    op.add_column('properties', sa.Column('construction_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'construction_year')
    op.drop_column('properties', 'heating')
    op.drop_column('properties', 'furnished')
    # ### end Alembic commands ###
