"""phase14 residential complexes

Revision ID: c9433bb97b4a
Revises: 38bab1bdf849
Create Date: 2026-08-15 20:29:23.463536

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c9433bb97b4a"
down_revision: str | None = "38bab1bdf849"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "residential_complexes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("developer_name", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("address_text", sa.String(length=500), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("district", sa.String(length=100), nullable=True),
        sa.Column("metro", sa.String(length=100), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("completion_year", sa.Integer(), nullable=True),
        sa.Column("total_units", sa.Integer(), nullable=True),
        sa.Column("cover_image", sa.String(length=500), nullable=True),
        sa.Column("amenities", sa.JSON(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_residential_complexes_city"),
        "residential_complexes",
        ["city"],
        unique=False,
    )
    op.create_index(
        op.f("ix_residential_complexes_slug"),
        "residential_complexes",
        ["slug"],
        unique=True,
    )
    op.create_index(
        op.f("ix_residential_complexes_status"),
        "residential_complexes",
        ["status"],
        unique=False,
    )
    op.add_column("properties", sa.Column("complex_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_properties_complex_id"), "properties", ["complex_id"], unique=False
    )
    op.create_foreign_key(
        None,
        "properties",
        "residential_complexes",
        ["complex_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "properties", type_="foreignkey")
    op.drop_index(op.f("ix_properties_complex_id"), table_name="properties")
    op.drop_column("properties", "complex_id")
    op.drop_index(
        op.f("ix_residential_complexes_status"), table_name="residential_complexes"
    )
    op.drop_index(
        op.f("ix_residential_complexes_slug"), table_name="residential_complexes"
    )
    op.drop_index(
        op.f("ix_residential_complexes_city"), table_name="residential_complexes"
    )
    op.drop_table("residential_complexes")
    # ### end Alembic commands ###
