"""phase15 make desktop_creative_url nullable

Revision ID: d61fd7758b3f
Revises: ac2100644a2a
Create Date: 2026-08-16 13:28:08.300042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd61fd7758b3f'
down_revision: Union[str, None] = 'ac2100644a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad_campaigns', 'desktop_creative_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ad_campaigns', 'desktop_creative_url',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
